{{- if .Values.cronJobs }}
{{- range $key, $val := .Values.cronJobs }}  
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Release.Name }}-cron{{$key}}
spec:
  schedule: {{ $val.schedule | quote}}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ $.Release.Name }}-cron{{$key}}
            image: {{ $val.image}}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - {{ $val.command | quote}}  
          restartPolicy: OnFailure
{{- end }}
{{- end }}
