# {{- range $key, $val := .Values.deployment }} 
# {{- if $val.keyvault }}
# {{- if $val.keyvault.data }}
# ---
# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: azkv-{{ $val.name | lower}}  # needs to be unique per namespace  
# spec:
#   provider: azure
#   parameters:
#     usePodIdentity: "false"
#     useVMManagedIdentity: "true"          
#     userAssignedIdentityID: {{ $.Values.keyvault.identityID}} # Setting this to use workload identity
#     keyvaultName: {{ $.Values.keyvault.name}}       # Set to the name of your key vault
#     cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
#     objects:  |
#       array:
#         {{- range $key_secret, $val_secret := $val.keyvault.data }}
#         - |
#           objectName: {{$val_secret.objectName}}
#           objectType: secret              
#           objectVersion: ""        
#         {{- end }}                           
#     tenantId: "67d00c3d-4d1e-41cc-93b4-74b100f49098"  
#   secretObjects:                             
#   - secretName: {{ $val.name }}-kv
#     data:
#     {{- range $key_secret, $val_secret := $val.keyvault.data }}
#     - key: {{$val_secret.key}}                         
#       objectName: {{$val_secret.objectName}}
#     {{- end }}                                      
#     type: Opaque
# {{- end }}
# {{- end }}
# {{- end }}